In [19]:
import cv2, numpy as np

In [20]:
cap = cv2.VideoCapture(0)

In [21]:
# Face Detection

In [22]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")

skip = 0

face_data = []

dataset_path = './data/'

file_name = input('Enter the name of the person : ')

while True:
    
    ret,frame = cap.read()
    face_section = frame
    if ret == False:
        continue
        
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    faces = sorted(faces,key = lambda f:f[2]*f[3])

    for face in faces[-1:]:
        x,y,w,h = face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
        #Extract (Crop out): Region of face
        offset = 10
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section = cv2.resize(face_section,(100,100))
        
        skip += 1
        if skip%10 == 0:
            face_data.append(face_section)
            print(len(face_data))
        
    
    cv2.imshow("Frame",frame)
    cv2.imshow("Face_Section",face_section)
    
    #Store every 10th face
    
    
#     if(skip%10 == 0):
#         pass
    
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
        

face_data = np.asarray(face_data)
face_data = face_data.reshape((face_data.shape[0],-1))
print(face_data)
print(face_data.shape)

np.save(dataset_path+file_name+'.npy',face_data)
print("Data successfully saved at "+ dataset_path+file_name+'.npy')

cap.release()
cv2.destroyAllWindows()

Enter the name of the person : Golu
1
2
3
4
5
6
7
8
9
10
11
[[ 67  64  77 ...  61  55  90]
 [ 17  16  29 ...  42  38  68]
 [ 24  26  41 ...  37  32  64]
 ...
 [ 34  34  48 ...  62  67 106]
 [ 42  37  57 ...  67  70 108]
 [ 88  74  87 ...  95 102 139]]
(11, 30000)
Data successfully saved at ./data/Golu.npy


In [19]:
faces

array([[321, 177, 223, 223]], dtype=int32)

In [20]:
type(faces)

numpy.ndarray

In [21]:
cv2.rectangle?